### ISSUE TITLE
Empty date fields are coerced to 1/1/1970

### ISSUE THREAD

**Issue by spikeheap** [spikeheap/labking#28]
Empty date fields in forms should not be sent to the server as 1/1/1970.

**Comment by spikeheap** [comment]
This issue is probably a non-bug. The server coerces the empty date to 1/1/1970, it's not caused by Angular.

We *could* pre-fill the dates with a default 1/1/1970 date so it's consistent, but that might look a bit weird.

**Comment by spikeheap** [comment]
When we submit empty dates they are coerced to 1/1/1970, but this is not the expectation, especially for optional values.

**Comment by dasads44** [comment]
This bug has re-emerged in the 1.0.0 build.

**Comment by spikeheap** [comment]
Hi @dasads44, sorry about that. I've rectified it (again). I'll collect and fix any other bugs and release again on Wednesday, but if you need it urgently it's easy enough to release before then. Cheers!
