### ISSUE TITLE
Set date minimum allowable value

### ISSUE THREAD

**Issue by spikeheap** [spikeheap/labking#29]
The server will reject any dates < 1/1/1753. This should be fed back to the user (or a minimum date set).

Also, valid date ranges are set for the dataset. These should be honoured in the UI.

**Comment by spikeheap** [comment]
Open questions for LabKey in our call today: 

> * How can we retrieve the validator specifications using the JS API?
> * Is there a way to discover failed validations on non-required fields? Invalid values seem to be coerced into nulls with a 200 response.

**Comment by spikeheap** [comment]
From the call with LabKey, it's not possible to retrieve the validators and ranges using the JavaScript API, though it would be possible (in theory) to update LabKey's API to provide this information. It was suggested this might work in cooperation with LabKey's dev team.

I think in the interim we can close this issue as it's not a small fix. What do you think @dasads44?

**Comment by dasads44** [comment]
I agree, it shouldn't pose too much of an issue in our current use case as we get enough information in the error message if a value is not valid. But it would be something potentially worth looking into with the labkey dev team.
