### ISSUE TITLE
Field order 

### ISSUE THREAD

**Issue by dasads44** [spikeheap/labking#54]
fields in the labking module to not follow the order in there set in the mange dataset view.

**Comment by spikeheap** [comment]
The field order isn't returned in the `DataSet` query, we can only get it from a participant's dataset result (this works even if there are 0 results).

To resolve this we'll need to drop our calls to the DataSetColumns endpoint and retrieve that information from the first request for a participant's data. While we're at it we can resolve #67 at the same time.

The result of this will be that the metadata for a dataset isn't stored centrally.
