### ISSUE TITLE
Drop down lists appearing blank.  

### ISSUE THREAD

**Issue by dasads44** [spikeheap/labking#55]
If the lists which define the drop down look ups do not contain both a key and label column the drop down appears blank in LabKing. They also appear blank if labels are assigned to the key and label columns.

**Comment by spikeheap** [comment]
Updated the default behaviour to use the key if a label isn't set. It _may_ be possible to extract the default label for a list from the metadata but it's not provided in the default response, but at least this approach stops the system from giving us blank fields and list items.
