### ISSUE TITLE
Text to large for drop down fields 

### ISSUE THREAD

**Issue by dasads44** [spikeheap/labking#56]
The bottom is cut off the text once entered into a look up field.

![image](https://cloud.githubusercontent.com/assets/12081908/7700001/974961de-fe13-11e4-804a-c234a7dd96d7.png)

**Comment by spikeheap** [comment]
Hi @dasads44, I think this is resolved by #53:
![overview___hepatitis](https://cloud.githubusercontent.com/assets/464482/7909749/9c06a834-0846-11e5-889b-16a9433b2f0b.png)

I need to roll out a new release for this change to take effect, which I'll do this week after ticking off a few more issues.
