### ISSUE TITLE
Modal forms for data entry

### ISSUE THREAD

**Issue by dasads44** [spikeheap/labking#58]
The existing data entry is edit in place. It would be better for the data to be displayed in a wide format and for the editing and adding on new data to be performed via modals .

**Comment by spikeheap** [comment]
This is almost there. Outstanding tasks:

- [ ] Form validation
- [ ] Edit button/icon for results
- [ ] Edit save
- [ ] Keep modal open if save fails
- [ ] Fix failing tests on Travis

**Comment by spikeheap** [comment]
This is working now, so we'll treat everything else as an enhancement or bug...
