### ISSUE TITLE
Notification when leaving without saving data

### ISSUE THREAD

**Issue by dasads44** [spikeheap/labking#59]
There are no notifications to warn the user that they are leaving a data entry screen, without saving the data they have entered.

**Comment by spikeheap** [comment]
Hi @dasads44, now that we've moved to a modal edit view this may no longer be necessary. We could prompt the user if they've added any information and then hit `cancel`, so I'd be interested to know what you think once you've tried the new modal version. Cheers!

**Comment by spikeheap** [comment]
Closing for now as we're moving to modals. We can always open it up again if necessary.
