### ISSUE TITLE
Data entry for summary datasets

### ISSUE THREAD

**Issue by dasads44** [spikeheap/labking#60]
Data entry should not be possible for summary datasets.

**Comment by spikeheap** [comment]
Hi @dasads44, I've been digging around in LabKey but I can't see a way to create summary datasets. I don't suppose you could tell me how you created them could you?

If you have one set up already could I grab a fresh export please?

**Comment by spikeheap** [comment]
To create a summary dataset:

* Go to `Data Views` -> `Database Enrolment`
* Select `Views` -> `Create` -> `Query Snapshot`

**Comment by spikeheap** [comment]
Hi @dasads44, I've just followed those steps to create a query snapshot, but the result for me is an editable table which I can add new rows to. I think I may have missed a step! Could you comment on here with the bit I've missed?

Cheers
Ryan

**Comment by dasads44** [comment]
You haven't missed a step but, i think you are selecting the wrong thing in the Data Views table.

You need to select the dataset which should appear at the bottom in uncategorized (unless you changed the definition and assigned it a category).

It should look like this;
![snapshot query screenshot](https://cloud.githubusercontent.com/assets/12081908/8206018/abb35210-14ed-11e5-97b0-5ac18a8065cf.png)

**Comment by spikeheap** [comment]
I've raised a fairly detailed support request about this issue with LabKey: https://www.labkey.org/issues/Oxford/Support%20Tickets/details.view?issueId=23647.

**Comment by spikeheap** [comment]
We've had an update from LabKey that this is a bug in the Study module. They've created an issue to track the fix, and it's scheduled for the 15.2 release.

**Comment by spikeheap** [comment]
I've checked a snapshot dataset using the latest version of LabKey, and the LabKing module correctly identifies them as snapshots and greys out the edit and delete icons for each record:
<img width="195" alt="overview___hep" src="https://cloud.githubusercontent.com/assets/464482/9090681/94bf51a4-3b93-11e5-984f-e6fbf83091f7.png">
